### ISSUE TITLE
如何删除一些特殊动态库文件？

### ISSUE THREAD

**Issue by ladmini** [cjsliuj/MachoHandle#1]
我发现有一些安装包里面会有一些特殊的动态库文件，比如"@executable_path/AppIcon40x13@3x.nibs"这个时候使用我们的方法好像去不掉。

**Comment by cjsliuj** [comment]
使用 - (void) removeLinkedDylib:(NSString *)link 方法
`比如： [machoHandle removeLinkedDylib: @"@executable_path/AppIcon40x13@3x.nibs"]`

**Comment by ladmini** [comment]
谢谢您这么及时的反馈，我就是用这种方法，但是发现去不掉，如果是一般的dylib没有问题，可以去掉，我明天再试试，如果还是不行的话到时候不知道我是否把那个ipa可以发给您帮我看下?

**Comment by cjsliuj** [comment]
恩 好

**Comment by ladmini** [comment]
您好，抱歉，昨天有点事情耽搁了，今天才答复您。我这边测试了一下，用的是您提供的Demo，发现还是移除不了。用到的相关文件如下，请帮忙看一下是哪里的问题，非常感谢!

[files.zip](https://github.com/cjsliuj/MachoHandle/files/3313775/files.zip)

**Comment by cjsliuj** [comment]
抱歉，这么晚回复，我看了你的demo，问题出在下面这句代码：
`removeDylibLink(machoHandler, @"@executable_path/executable_path/AppIcon40x13@3x.nibs");`
替换为：
`removeDylibLink(machoHandler, @"@executable_path/AppIcon40x13@3x.nibs");`

你可以用 otool -L #macho path# ，命令查看当前所有的动态库。
![1](https://user-images.githubusercontent.com/4098790/60109463-f99cb580-979c-11e9-9c23-e9a721f957fb.png)
